### ISSUE TITLE
How to change header text styling when a dropdown is open?

### ISSUE THREAD

**Issue by Absleepy** [rsdavis/svelte-collapsible#14]
I want to make my question's text bold when someone opens a dropdown. But it seems to have no option for it.
Can someone please guide or add this option?

Thank You!

**Comment by samal-rasmussen** [comment]
Use the aria-expanded attribute on the li.

```css
:global(li.accordion-item[aria-expanded="true"] p) {
  font-weight: bold;
}
```

Example repl here:
https://svelte.dev/repl/3ffbbb81312240f39fde7570872c6d7e?version=4.2.2

This currently gives an A11y error and I'm proposing to change this to an `open` class instead to fix that:
https://github.com/rsdavis/svelte-collapsible/pull/16
